# A structure for tracking individual changes to a record.
Audit::Change = Struct.new(:attribute, :old_value, :new_value)

# A structure for tracking an atomic group of changes to a model.
class Audit::Changeset < Struct.new(:changes)
  
  # Recreate a changeset given change data as generated by ActiveRecord.
  #
  # hsh - the Hash to convert to a Changeset
  #
  # Examples:
  #
  #   Audit::Changeset.from_hash({'age' => [30, 31]})
  #   # [<struct Audit::Changeset @attribute="age" @old_value=30 
  #   #  @new_value=31>]
  # 
  # Returns an Array of Changeset objects, one for each atomic change
  def self.from_hash(hsh)
    changes = hsh.map do |k, v|
      attribute = k
      old_value = v.first
      new_value = v.last
      Audit::Change.new(attribute, old_value, new_value)
    end
    new(changes)
  end
  
end
